inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: true

Gemspec/RequireMFA:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

RSpec/ContextWording:
  Enabled: false

# Savon::BlockInterface calls block.binding, which fails
# on C-level procs created by Symbol#to_proc.
Style/SymbolProc:
  Exclude:
    - 'spec/savon/options_spec.rb'
