name: Push gem
on:
  release:
    types: [published]
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: release
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: "3"
          bundler-cache: false
      - name: Install dependencies
        run: bundle install
      - uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7 # v1.2.0
