name: Push gem
on:
  release:
    types: [published]
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: "3"
          bundler-cache: false
      - name: Install dependencies
        run: bundle install
      - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1
